### ISSUE TITLE
Document passkeys recovery security

### ISSUE THREAD

**Issue by MasterKale** [passkeydeveloper/passkeys.dev#107]
### Summary

Plenty of people are assuming that owning of an iCloud, Google, or Microsoft account means the attacker also gains access to passkeys associated with that account. However Apple and Google (and assuming Microsoft too) implement additional measures to protect the passkeys private key material, which require attackers to glean additional info like the victim's local device unlock code to then decrypt the key material on an attacker-owned device.

These additional protections should be emphasized on the site for easy reference. Specifically these whitepapers that have been publicly published by Apple and Google:

- https://support.apple.com/en-us/HT213305
- https://security.googleblog.com/2022/10/SecurityofPasskeysintheGooglePasswordManager.html

### Proposed Content Type

Protocol Deep Dive

**Comment by timcappalli** [comment]
@MasterKale the reference pages have links to each of these. Are you wanting to add additional detail or is this complete?

**Comment by MasterKale** [comment]
There's probably no need for this anymore if that's the case. I'll close this out.
