### ISSUE TITLE
Apple ecosystem does not support UV requirement on external authenticators when no PIN is set

### ISSUE THREAD

**Issue by git14** [passkeydeveloper/passkeys.dev#122]
# Issue with existing content
Currently, the Apple ecosystem, does not support creating a FIDO credential on a security key with UV required when there is no PIN set on the security key.

Not all use cases for the basic FIDO flows are supported.

## Link to content

https://passkeys.dev/docs/reference/ios/
https://passkeys.dev/docs/reference/macos/

### What is the issue?

Clear steps describing how to reproduce the issue.

Platform: MacOS

1. Grab your favorite FIDO security key.
2. Reset the security key to ensure there is no PIN set.
3. Sign into a favorite FIDO test site in Safari, https://webauthntest.identitystandards.io/login.html
4. Set the create credential option drop down for User Verification to Required.
5. Create the credential.
6. Request UI completes successfully, but there was no prompt to set a PIN and the UV flag returned is 0.

Repeat the same steps on iOS with the same results.

### Proposed changes

Recommendation is to change the green Supported badge to the yellow Partially Supported badge for external authenticators on both iOS and MacOS pages.

**Comment by timcappalli** [comment]
passkeys.dev does not currently cover security keys. We can add this information when we add security key information later in 2023.

**Comment by timcappalli** [comment]
Ah I see what you mean now. I will add a caveat to the Apple pages. Thanks for pointing this out!

**Comment by timcappalli** [comment]
Added! Thank you @git14!
