### ISSUE TITLE
Capture hybrid registration and authentication behavior in Device Support

### ISSUE THREAD

**Issue by MasterKale** [passkeydeveloper/passkeys.dev#141]
### Summary

There are currently some hybrid registration and authentication idiosyncracies that might be nice to capture on the Device Support page. For example:

- If you check the "remember this connection" (paraphrasing for now) box during hybrid registration, Chrome will remember your Android device and forego future QR code scanning for authentication by showing your phone as an authentication option
- iOS always requires scanning a QR code during authentication

Capturing these current behaviors would make it easy to share around these nuances because afaik there's no good place to go to reference such behavior.

### Proposed Content Type

FAQ Item

**Comment by timcappalli** [comment]
We can put these on the platform notes pages.

I'm afraid of adding more stuff to the matrix, especially things that technically don't affect "readiness to deploy".

**Comment by MasterKale** [comment]
Oh, platform pages sound like a good match for this too 🤔
