### ISSUE TITLE
Device Support Matrix - More visibility for Security Keys

### ISSUE THREAD

**Issue by csalas-yubico** [passkeydeveloper/passkeys.dev#17]
# Issue with existing content
I want to propose giving more "visibility" to security keys in the Device Support Matrix. Right now it is referenced as a footnote, and might not be immediately clear for someone looking to learn how security keys fit into the concept of passkeys. Someone knowledgeable in WebAuthn might recognize that the non-support for single device passkeys is due to the platform authenticator, and not a limitation on external devices (with the exception of Android not currently supporting discoverable credentials)

## Link to content
https://passkeydeveloper.github.io/passkeys.dev/device-support/

## Proposed changes

My recommendation:
Have two rows in the "Single-device passkeys"  section: 
* One to note if single device passkeys are supported on the platform authentication
* One to note if single device passkeys are supported on security keys

If we don't want to refer to the first item as "platform authenticator" we can reference it by the common vendor name (Windows Hello, Face/Touch ID, etc..)

**Comment by timcappalli** [comment]
addressed in b2bdf6026b3ee91eee4556023244a1f791458117
