### ISSUE TITLE
Link on "exclude list" in opt-in docs points to homepage

### ISSUE THREAD

**Issue by MasterKale** [passkeydeveloper/passkeys.dev#219]
# Issue with existing content

## Link to content

https://passkeys.dev/docs/use-cases/bootstrapping/#opting-the-user-into-passkeys

### What is the issue?

The link on "exclude list" here points to the homepage:

![Screenshot 2023-06-27 at 9 21 00 AM](https://github.com/passkeydeveloper/passkeys.dev/assets/5166470/13e61b34-4bb6-4102-89e9-11f77f596935)

### Proposed changes

I don't see an entry for "exclude list" on our Terms page, so maybe this is supposed to point to L2? Here maybe?

https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialcreationoptions-excludecredentials

### Any other notes

N/A

**Comment by timcappalli** [comment]
added via 3fb9d033354ee6650c0d5d0fd4017fb9a6a62030
