### ISSUE TITLE
Could do with a definition of "Persistent linking"

### ISSUE THREAD

**Issue by adrianhallnhsd** [passkeydeveloper/passkeys.dev#220]
### Summary

The term "Persistent linking" is used many times, but there is no definition of what this means, or why iOS doesn't support it. 

I've tried searching wider than this site, and there is no mention of it anywhere else in relation to passkeys or webauthn. 

### Proposed Content Type

Other / Unknown

### Proposed Content Title

Persistent linking

**Comment by timcappalli** [comment]
@adrianhallnhsd see #228
