### ISSUE TITLE
Proposed change to the About page

### ISSUE THREAD

**Issue by dturnerx** [passkeydeveloper/passkeys.dev#221]
# Issue with existing content
A concern was raised by a FIDO member about this sentence on the About page: 

"passkeys.dev is brought to you by the [W3C WebAuthn Community Adoption Group](https://www.w3.org/community/webauthn-adoption/) and the [FIDO Alliance](https://fidoalliance.org/)."

## Link to content
https://passkeys.dev/about/

### What is the issue?
The member is concerned that the current sentence implies that the content on this site has been reviewed and approved for publication by the FIDO Alliance according to the FIDO Alliance processes. 

### Proposed changes

Change "and the FIDO Alliance" to "and members of the FIDO Alliance."

**Comment by MasterKale** [comment]
Seems like a reasonable ask to me, stay tuned for tweaked verbiage ✌️
