### ISSUE TITLE
Password Managers-related Content

### ISSUE THREAD

**Issue by mhalano** [passkeydeveloper/passkeys.dev#237]
### Summary

The idea is to add content related to support to Passkeys with the most common password managers (1Password already have support and IIRC Lastpass will have support soon).
I can use Passkeys with Ubuntu when I'm using Firefox or Chrome with the 1Password extension (support still in beta).
The Linux app already support saving the credentials and showing in the user interface.

### Proposed Content Type

Other / Unknown

### Related Articles

- https://support.1password.com/save-use-passkeys/
- https://blog.lastpass.com/2023/06/support-for-passkeys-coming-later-this-year/

**Comment by timcappalli** [comment]
We currently don't have any plans to cover 3P passkey providers, especially given that most implementations are currently "hacks" using browser extensions.

I will leave the issue open though for future consideration.

**Comment by irew** [comment]
> We currently don't have any plans to cover 3P passkey providers, especially given that most implementations are currently "hacks" using browser extensions.
> 
> I will leave the issue open though for future consideration.

I take offence to such a characterisation 😛 - we're weeks away from Android 14 and iOS 17 going GA, which is when we'll see 3rd party apps support passkeys in a pluggable manner.

My 2c:
I consider browser extension based passkey support legitimate, the reason being that desktop OS support and rollout may take **years** before we see wide-scale use of OS pluggable solutions on desktop. That's not necessarily when the platform vendors will ship the OS update, but when most people will have access to that OS update, people tend to hold on to laptops a lot longer than mobile devices, so many users may not be able to update to the relevant OS version. The OS update cycle is longer and slower on desktop than on mobile, these 3rd party providers need to provide a meaningful solution in the meantime. During this time, I expect browser extensions will be the more widespread method of providing passkeys support for the vast majority of 3rd party services.

**Comment by timcappalli** [comment]
This has been addressed over time in the Device Support matrix.
