### ISSUE TITLE
Add PASS by SKT

### ISSUE THREAD

**Issue by Kieun** [passkeydeveloper/passkeys.dev#275]
### Type

New service

### Service Name

PASS by SKT

### Service URL

https://www.sktpass.com/

### Web

- [ ] Supported

### Apps

- [X] Supported

### Notes

Adoptions
- iOS only (username-less approach with client side storage)
- Android: device bound fido2 credential (as of oct.)

Application store
- Android: https://play.google.com/store/apps/details?id=com.sktelecom.tauth
- iOS: https://apps.apple.com/kr/app/id1141258007

### Links

- Articles: https://www.frontier-enterprise.com/sk-telecom-unlocks-passwordless-future/

### Contact

- [X] I am

**Comment by timcappalli** [comment]
Given passkeys are only being used on iOS, this doesn't really qualify to be included in the list. 

The list on passkeys.dev is a curated list, not a general-purpose directory.
