### ISSUE TITLE
Add Microsoft 365 Personal

### ISSUE THREAD

**Issue by BakkerJan** [passkeydeveloper/passkeys.dev#277]
### Type

New service

### Service Name

Microsoft 365 Personal

### Service URL

https://www.microsoft365.com/

### Web

- [X] Supported

### Apps

- [ ] Supported

### Notes

Use Windows Hello to sign in to your account
This method can also be used to add a passkey in a supported password manager (1Password for example)

### Contact

- [ ] I am

**Comment by BakkerJan** [comment]
https://support.microsoft.com/en-us/windows/sign-in-to-your-microsoft-account-with-windows-hello-or-a-security-key-800a8c01-6b61-49f5-0660-c2159bea4d84

**Comment by BakkerJan** [comment]
Notes: Click the setup link and sign in with your email address and password, then click "Add a new way to sign in or verify", choose Use your Windows PC, and follow the steps to create a passkey.

Sign out, then choose "Sign in with Windows Hello or a security key" when you sign back in to use your passkey.

**Comment by timcappalli** [comment]
Please keep in mind that this list isn't a general purpose "here's where passkeys are supported" list.

Synced passkeys and related experiences are not yet officially supported for Microsoft accounts.
