### ISSUE TITLE
Add Apple

### ISSUE THREAD

**Issue by NathanHannon** [passkeydeveloper/passkeys.dev#279]
### Type

New service

### Service Name

Apple

### Service URL

https://apple.com

### Web

- [X] Supported

### Apps

- [X] Supported

### Notes

Passkeys were generated for all iCloud users by Apple and can be used to log in to Apple's websites. Its only available on iOS 17+

### Links

https://www.theverge.com/2023/6/20/23767583/apple-iphone-ios-17-beta-passkey

### Contact

- [ ] I am

**Comment by timcappalli** [comment]
Please keep in mind that this list isn't a general purpose "here's where passkeys are supported" list.

Many passkeys experiences are not currently available for Apple IDs so it will not be included at this time.
