### ISSUE TITLE
Passkey providers via a browser extension

### ISSUE THREAD

**Issue by irew** [passkeydeveloper/passkeys.dev#280]
# Existing content does not mention browser extensions as a way of providing passkey support

## Link to content
https://github.com/passkeydeveloper/passkeys.dev/blob/464d98d952fe066a4d890843d540ef74f1d43806/content/en/docs/reference/terms/index.md?plain=1#L167

### What is the issue?

Many 3rd party passkey providers, password managers, provide support for passkeys via a browser extension. The audience reading content on this site, who may be implementing passkeys need to be aware of this and test against it during development. As an example, decisions may be made based on user agent info (version of macOS etc) to create UX that tells their users whether or not a passkey can be saved to their password manager, we've seen this already in the wild.

This is a reality their users will face so it should be accounted for in some manner.

### Proposed changes

Browser extensions that handle passkeys should be mentioned in the documentation in some way. Even if it is to say something along the lines of "some passkey providers provide support via a browser extension, which can be considered a temporary solution while a more robust solution is being developed."

### Any other notes

Password managers that support passkeys via a browser extension:

- 1Password
- LastPass
- Bitwarden (planned)
- Keeper Security
- NordPass

**Comment by hex-m** [comment]
KeePassXC [just implemented Passkeys](https://github.com/keepassxreboot/keepassxc/pull/8825).
