### ISSUE TITLE
Library listed for Go is deprecated

### ISSUE THREAD

**Issue by dbarkwell** [passkeydeveloper/passkeys.dev#284]
# Issue with existing content

The library for Go that is linked to is deprecated.

## Link to content

https://passkeys.dev/docs/tools-libraries/libraries/#go

### What is the issue?

The repo for the Go library states that the library is deprecated and recommends using the forked repository.

### Proposed changes

The Go library should be linked to: https://github.com/go-webauthn/webauthn or provide both libraries with a note that the Duo Labs library is deprecated.

**Comment by MasterKale** [comment]
As the person who facilitated the transfer of the Golang version out of Duo Labs, let's _not_ list the Duo Labs version alongside the maintained one. It'd create unnecessary confusion.

**Comment by timcappalli** [comment]
Thanks @dbarkwell! Addressed in 7601c1b.
