### ISSUE TITLE
Add Coinbase

### ISSUE THREAD

**Issue by pierre-yves-cb** [passkeydeveloper/passkeys.dev#299]
### Type

New service

### Service Name

Coinbase

### Service URL

coinbase.com

### Web

- [X] Supported

### Apps

- [X] Supported

### Links

[Help](https://help.coinbase.com/en/coinbase/getting-started/getting-started-with-coinbase/passkeys)

### Contact

- [X] I am

**Comment by timcappalli** [comment]
Coinbase requires both an OTP and an email confirmation after signing in with a passkey. This is a bit of an anti-pattern for passkeys so unfortunately I won't be able to add Coinbase as a featured deployment.

**Comment by kzaky** [comment]
I am curious why there is still a need for OTP (phishable) after a passkey (non-phishable). Besides the redundancy for security verification wouldn't this complicate the user experience?

**Comment by pierre-yves-cb** [comment]
Ack.  OTP is triggered depending on a experiment which we might remove in the future or not. Some users might not have OTP triggered.

**Comment by pierre-yves-cb** [comment]
Similarly for email confirmation triggered on new device - it is depending on a an experiment that we might remove in the future or not. Some users might not have email confirmation triggered.

**Comment by timcappalli** [comment]
Closing for reasons mentioned in https://github.com/passkeydeveloper/passkeys.dev/issues/299#issuecomment-1823273276
