### ISSUE TITLE
Add AppMaster

### ISSUE THREAD

**Issue by OlegSotnikov** [passkeydeveloper/passkeys.dev#311]
### Type

New service

### Service Name

AppMaster

### Service URL

https://appmaster.io

### Web

- [X] Supported

### Apps

- [X] Supported

### Notes

* Limited to a single passkey in AppMaster Studio.
** Applications created in AppMaster Studio support Passkey by default in Backend, Web, Android and IOS application.

### Contact

- [X] I am

**Comment by timcappalli** [comment]
This appears to be a PaaS and not an end user resource.
