### ISSUE TITLE
Add PlayStation

### ISSUE THREAD

**Issue by dcoles** [passkeydeveloper/passkeys.dev#343]
### Type

New service

### Service Name

PlayStation

### Service URL

https://www.playstation.com

### Web

- [X] Supported

### Apps

- [X] Supported

### Notes

Was very excited to see that PlayStation now support Passkeys. Technically they're Sony accounts, but PlayStation is the user-facing brand.

### Links

https://www.playstation.com/en-us/passkey/

### Contact

- [ ] I am

**Comment by timcappalli** [comment]
This section has been removed from the site. (#397)
