### ISSUE TITLE
Add Amazon

### ISSUE THREAD

**Issue by tblachowicz** [passkeydeveloper/passkeys.dev#368]
### Type
New service
 
### Service Name
Amazon

### Service URL
* https://amazon.com
* https://amazon.pl
* https://amazon.de
* https://amazon.co.uk
* https://amazon.ie
 
### Web
* [x]  Supported
 
### Apps
* [x]  Supported

### Notes

Amazon supports passkeys globally for many markets.

### Links
[About Passkey](https://www.amazon.com/gp/help/customer/display.html?nodeId=TPphmhSWBgcI9Ak87p)
 
### Contact
 * [ ]  I am

**Comment by timcappalli** [comment]
Amazon still requires an OTP when using a passkey. The only way to fix this is to disable 2FA, which then leaves your password usable without a second factor.
