### ISSUE TITLE
Add Discord

### ISSUE THREAD

**Issue by tblachowicz** [passkeydeveloper/passkeys.dev#369]
### Type
New service
 
### Service Name
Amazon

### Service URL
* https://discord.com
 
### Web
* [x]  Supported
 
### Apps
* [x]  Supported

### Notes

Discord supports passkeys as second factor on top of the passwords.

### Links
[Setting up Multi-Factor Authentication](https://support.discord.com/hc/en-us/articles/219576828-Setting-up-Multi-Factor-Authentication)
 
### Contact
 * [ ]  I am

**Comment by timcappalli** [comment]
> Discord supports passkeys as second factor on top of the passwords.

This is why it isn't included on the list. The page is designed to represent best practice deployments with a good UX.

**Comment by tblachowicz** [comment]
Ok. Understand. Thanks!
