### ISSUE TITLE
Add Coinbase

### ISSUE THREAD

**Issue by tblachowicz** [passkeydeveloper/passkeys.dev#370]
### Type
New service
 
### Service Name
Coinbase

### Service URL
* https://coinbase.com
 
### Web
* [x]  Supported
 
### Apps
* [x]  Supported

### Notes

Coinbase supports passkeys as the second factor on top of the passwords.

### Links
[Introducing Passkeys: A Safer and Easier Way to Sign in to Coinbase](https://www.coinbase.com/en-gb/blog/introducing-passkeys-a-safer-and-easier-way-to-sign-in-to-coinbase)
 
### Contact
 * [ ]  I am

**Comment by timcappalli** [comment]
see: https://github.com/passkeydeveloper/passkeys.dev/issues/299
