### ISSUE TITLE
Link to request new active deployment is broken

### ISSUE THREAD

**Issue by tblachowicz** [passkeydeveloper/passkeys.dev#371]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

1. Navigate to [Active Deployments](https://passkeys.dev/docs/demos-examples/active-deployments/)
2. Clik [create an issue](https://github.com/passkeydeveloper/passkeys.dev/issues/new?assignees=&labels=&projects=&template=active-deployments.yml&title=Add+%3Cservice+name%3E) link

### Expected result

User should be taken to the Active Deployments template with prefilled content

### Actual result

User is taken to the list of issue templates (https://github.com/passkeydeveloper/passkeys.dev/issues/new/choose). The list itself does not contain the appropriate template for requesting to add new deployment to the Active Deployments site.

### Environment

N/A

**Comment by timcappalli** [comment]
Thanks. We removed this issue type and forgot to update the page.
