### ISSUE TITLE
Not all Android 14+ devices support Third-Party Passkey Providers

### ISSUE THREAD

**Issue by mimi89999** [passkeydeveloper/passkeys.dev#390]
# Issue with existing content

## Link to content

https://passkeys.dev/device-support/

### What is the issue?

Third-Party Passkey Providers are marked as supported by Android 14+

### Proposed changes

Not all Android 14+ devices support Third-Party Passkey Providers. It's an optional Android feature. Vendors can decide whether to enable that feature.

### Any other notes

Please see https://issuetracker.google.com/issues/349310440 and the linked issues

**Comment by timcappalli** [comment]
Yes, I'll add a small mention, but this bug does not impact relying parties.
