### ISSUE TITLE
Fix device support matrix on mobile 

### ISSUE THREAD

**Issue by timcappalli** [passkeydeveloper/passkeys.dev#59]
Make the left sticky column translucent when scrolling on mobile

![Screenshot_20221017-132840.png](https://user-images.githubusercontent.com/6476604/196278115-517b754a-dd38-4243-90e9-b67709ddc89c.png)

**Comment by MasterKale** [comment]
This only appears to be an issue with the light mode styles:

**Light:**

![image](https://user-images.githubusercontent.com/5166470/196279608-f0c3a4f7-d8a1-42e2-830c-c54f1ac745eb.png)

**Dark:**

![image](https://user-images.githubusercontent.com/5166470/196279635-b22f13ba-320b-4705-8969-5d8fcfcc8b7a.png)

**Comment by mkkhedawat** [comment]
In light mode, Background colour of sticky column is transparent, So the underneath text is visible. Need to override the same.
