### ISSUE TITLE
Improve advice in bootstrapping document.

### ISSUE THREAD

**Issue by Firstyear** [passkeydeveloper/passkeys.dev#63]
## Description

A number of the steps on the bootstrapping ( https://passkeys.dev/docs/use-cases/bootstrapping/ )  page are problematic for RPs.  The intent of passkeys are to replace passwords, then we must ensure they work in the broadest set of cases for all users. Any barriers to this will alienate people and hinder adoption. Currently the advice on this document will limit and prevent users from being able to effectively use passkeys. Since you have positioned yourself as "the authority" on what passkeys are and developers will follow your lead - without realising that this may be problematic for users.

- encouraging JS to override / set pubKeyCredParams

Remedy: This should be from the server provided information - not determined by the client. 

- authenticatorAttachment: platform

This is not always possible to satisfy. For example, consider my windows 10 gaming PC which lacks a TPM. I would require my iphone with caBLE which is excluded by this policy since it is a cross-platform authenticator. Also consider people with different ecosystems with incompatible sync fabrics such as an android user wanting to authenticate on a mac platform. It is not possible to satisfy with "platform" only. 

Additionally, not allow browsers and OS combinations support platform authenticators. For example Firefox on MacOS or Linux does *not* support platform based authenticators, only supporting CTAP1. (2022-10-19). As a result, this would completely exclude those users. 

Finally, the "attitude" of the webauthn wg is that users in a public (non-enterprise) facing context should always have choice of their authenticator used. Many users, especially technical users will wish to continue to use their existing fido2 devices such as yubikey.s

Remedy: This should not be set, or explicitly set to allow both platform and non platform.

- residentKey: required
 
This is not always possible to provide. While many platform authenticators will always create residentkeys such as apple passkeys, as we established above we can not rely on platform authenticators as the sole device type. Since we must now accept that *any* possible authenticator may be used we must consider that the vast majority of devices such as yubikeys, nitrokeys, and others have finite space for resident keys. Some keys support as few as 8, where yubikeys commonly support 25. This pales in comparison to many users number of sites they access, where many people will have 50 or more passwords stored. Just because there are some keys that support 100+ resident keys, does not mean that everyone will have or want to use them!

Since we want to encourage *all people* to use passkeys, and use cryptographic authentication, key residency should be considered an opportunistic property, not a guarantee. This will allow users the choice and freedom to use the keys they want, without artificial or user hostile limitations.  

Remedy: Do not set the residentKey: required parameter

- userVerification: required

As previously mentioned, there are many people using firefox as a browser. Firefox *does not* support CTAP2 yet, and is unable to provide user verification. As a result, this policy would prevent people from using that browser with your passkey configuration. 

Remedy: set userVerification - preferred, and track the uv state from registration to ensure it is enforced on a per-authenticator level.

**Comment by riking** [comment]
> * encouraging JS to override / set pubKeyCredParams
> 
> Remedy: This should be from the server provided information - not determined by the client.

If the server controls the JS, this advice is useless. The server should instead verify that the data it receives matches the restrictions

**Comment by Firstyear** [comment]
The js shouldn't muck with stuff that the server gives it, because you're just going to create a scenario where the user's enrollment will fail.

**Comment by My1** [comment]
I also wanna throw something in.

1) platform only is not only affecting Firefox on Linux, but to my knowledge there are neither platform authenticators for Linux nor browsers playing with any in the first place.

2) as said, rk numbers are very fluctuating and while usernameless login is cool it shouldn't be thrown out too much especially when you not only habe low numbers on some keys, others also have CD-RW style rk management meaning the only way to clear an RK is to just WIPE EVERYTHING (even server-stored keys wouldnt work anymore after that. not cool.

3) for UV stuff is more complicated. Passwordless has always been dropped in the context of having 2 factors, like device and pin, or device and biometrics

The biggest issue is that if you set preferred and track stuff you still get the issue that if the user sits in front of Firefox later on that's a nice uv bypass.

This is in my opinion something where Firefox needs to pull its weight.

Fido2 was introduced more or less with the yubi5 September 2018 which is 4 years ago. I think this could turn into an internet explorer-esque situation which would suck.

4) going passkey only leads to more issues than just not able to use roaming devices.

I mean you first get lock in (and lock-out) effects e.g. If you used an iPhone before and switched to an android, have fun recovering your digital identity, problem is also that webauthn with passkeys majorly trivializes authentication making it even less likely for people to even think about it.

Second, with a synced credential, while convenient you get the issue that you cannot revoke individual devices, which can also be a problem.

Third, when you go passwordless aside from the trust issues (especially as ALL THREE passkey providers sit in the us, which has HORRIBLE privacy laws including the cloud act which would force access even across subsidiaries) you get a cyclic dependency (or need to fall back to password) to actually get access to the passkeys in the first place when you lose your phone.)

**Comment by My1** [comment]
Another thing that might be great for the future might be an option for rk to just not say preferred or required but rather also have options like "ask the user if roaming" or "not if roaming
", where then roaming authenticators could be tactically excluded or get a prompt (which can inform both on the amount of RKs left and if they can be thrown out individually)

**Comment by Firstyear** [comment]
This issue isn't stale, it's still a problem. @timcappalli @iamkale can you remove this label and actually act on this?

**Comment by timcappalli** [comment]
From the CG meeting on 2022-12-05:

> encouraging JS to override / set pubKeyCredParams

Agree that this should be spelled out. https://github.com/passkeydeveloper/passkeys.dev/issues/101

> authenticatorAttachment: platform

Agreed.

> residentKey: required

Passkeys are an opinionated implementation of WebAuthn with multiple components including autofill UI. A passkey must be a discoverable credential and thus this guidance will remain as is.

> userVerification: required

This is already being changed in PR #100

**Comment by Firstyear** [comment]
> Passkeys are an opinionated implementation of WebAuthn with multiple components including autofill UI. A passkey must be a discoverable credential and thus this guidance will remain as is.

A passkey doesn't force autofill. There is no definition of a passkey agreed by the webauthn wg - only what you believe you want it to be. Because there is no true consensus I am trying to warn you that the model you are trying to establish will be problematic for users in many cases especially when limited credential storage devices are in use.

You are looking at this from a perfect world model, and you are effectively saying there are classes of users who's experience you don't care about.

I am trying to say that there are users who will be alienated if people follow your advice. We don't live in the perfect world you hope for. 

Time and time and time again the webauthn wg have said users are free to bring any device they choose. The end goal of the webauthn wg is to replace passwords, to allow devices as identity. And a key part of that is users can choose the devices they want to use. This means we must accept that *mixed authenticator use cases will exist* where providers need to support mixing of "passkeys" with yubikeys or other authenticators. Because webauthn as a standard is too coarse, we need to use the lowest supported common denominator.

Please, please reconsider. You have unilaterally nominated yourself as "the king of what passkeys are" without any community engagement. Because of this, people will look to you for guidance and today your guidance risks rejecting and alienating users. This is the opposite of how I interpret the goals of the webauthn wg.

Discoverability is opportunistic, and not a required property since not all devices that users choose to use will support this or have limited storage. Please change this.

**Comment by timcappalli** [comment]
I don't find your continued personal digs at me acceptable and I will no longer be directly engaging with you, @Firstyear.

**Comment by Firstyear** [comment]
Fine. Have fun.
