### ISSUE TITLE
Please add webauthn-rs to libraries section.

### ISSUE THREAD

**Issue by Firstyear** [passkeydeveloper/passkeys.dev#64]
https://passkeys.dev/docs/tools-libraries/libraries/

The library https://crates.io/crates/webauthn-rs supports passkeys and has properly tested passkey handling. This is documented here: https://docs.rs/webauthn-rs/latest/webauthn_rs/struct.Webauthn.html 

Please add webauthn-rs to the list of libraries.

**Comment by timcappalli** [comment]
done, thanks!
