### ISSUE TITLE
Authenticator Attachment reference - macOS

### ISSUE THREAD

**Issue by timcappalli** [passkeydeveloper/passkeys.dev#66]
### Summary

Document the different behaviors across browsers for the different authenticator attachment options (including screenshot examples).

### Details

Example: 

### Windows

Not specifying an authenticator attachment results in the following experience. < explanation > < animated screenshots >

### Proposed Content Type

Protocol Deep Dive

**Comment by MasterKale** [comment]
I'm going to create another similar issue for updating the Windows docs, to help keep content updates bite-sized.
