### ISSUE TITLE
Add Passage Demo to Test and Demo's page

### ISSUE THREAD

**Issue by PassageNick** [passkeydeveloper/passkeys.dev#71]
# Issue with existing content

The Test and Demos page only includes some of the demo sites out there.

## Link to content

https://passkeys.dev/docs/tools-libraries/test-sites/

### What is the issue?

There are more demo sites out there than the ones listed.

### Proposed changes

I propose that 

[https://passage.id/demo](https://passage.id/demo)

be added to the Test and Demos page

### Any other notes

I'm the Developer Advocate from Passage.  I saw that Yubikey's demo was there, so I thought to suggest our demo page be added.  

Passage is a member of the FIDO Alliance.

**Comment by timcappalli** [comment]
@PassageNick this site is more of a product pitch than a technology demo so unfortunately, we cannot include it at this time.

**Comment by PassageNick** [comment]
Hmm -- saw the Yubico demo site, and thought it would be okay.

No worries, thanks!
