### ISSUE TITLE
Add webview support in Device Support section

### ISSUE THREAD

**Issue by Kieun** [passkeydeveloper/passkeys.dev#83]
### Summary

Some platforms supports Webauthn API in In-app browsers.
It would be good to have such information in passkey.dev.

As far as I know, Android webview still does not support Webauthn API.

### Proposed Content Type

Other / Unknown

### Proposed Content Title

Device support

**Comment by timcappalli** [comment]
@Kieun, WebAuthn is supported via CCTs on Android. 

We can potentially add this to each of the individual platform pages, but likely will not add it to the matrix, as there are too many combinations.

**Comment by Kieun** [comment]
@timcappalli It would be helpful to add such information in somewhere. In practical, many of apps still leverage just webview as an in-app browser.

**Comment by timcappalli** [comment]
2023-09-15 call: add a new native app capabilities twirl down that covers EWV and SWV.
