### ISSUE TITLE
Improve non-discoverable credential description

### ISSUE THREAD

**Issue by Kieun** [passkeydeveloper/passkeys.dev#84]
# Issue with existing content

## Link to content
https://passkeys.dev/docs/reference/terms/#discoverable-credential

### What is the issue?
The document describes non-discoverable credential as follows. But, the non-discoverable credential is not the U2F credential. Although, U2F credential is a type of non-discoverable credential. But, Android single-device credential also does not support resident key features.

> In contrast, a non-discoverable credential (also known as a U2F credential) is encrypted by the authenticator and stored by the RP

### Proposed changes

I recommend the changes of the description.

> also known as a U2F credential -> U2F credential is one of such credentials

**Comment by timcappalli** [comment]
@Kieun, an Android non-discoverable credential is a U2F-style credential that is exercised via the WebAuthn API.

**Comment by Kieun** [comment]
@timcappalli But, in case of android, the attestation format is safetynet and it's not U2F credential. I understand the meaning and it's intention. But, someone might misunderstand. Also, even future x, y, z authenticator might support non-discoverable credential. Although, it's likely not happened.

**Comment by timcappalli** [comment]
I will just remove the reference to non-discoverable credentials are they are not relevant for passkeys.
