### ISSUE TITLE
Detailed UX guideline

### ISSUE THREAD

**Issue by Kieun** [passkeydeveloper/passkeys.dev#85]
### Summary

After introducing discoverable credentials, conditional mediation and passkeys, RP might have a variety way of prompt user authentication. Depending on the implementation or the provided options from the RP, the UI might be provided differently by the platforms or browsers.
It would be great to provide such UI examples (or screenshots) per the provided options.

Plus, some of the registration options are used and displayed for the passkey proposal or account selection. 
E.g., user.name, user.displayName, rp.id, rp.name and etc.
Although there are small rooms to customize the UI by the RP, RP would like to know how platforms and browsers present such information to the user.

### Proposed Content Type

User Journey

**Comment by hisgarden** [comment]
@Kieun : we could start with FIDO Design Systems, especially platform authenticator user journeys: https://fidoalliance.org/ux-guidelines/desktop-authenticator-ux-guidelines/

**Comment by Kieun** [comment]
@hisgarden Thanks for the information. The resource is great. But, at the moment, it is lack of passkey related guideline.

**Comment by timcappalli** [comment]
FIDO now has dedicated UX guidance.
