### ISSUE TITLE
Conditional UI guidance assumes non-promise-based PublicKeyCredential.isConditionalMediationSupported

### ISSUE THREAD

**Issue by sbweeden** [passkeydeveloper/passkeys.dev#98]
# Issue with existing content

## Link to content

See: https://passkeys.dev/docs/use-cases/bootstrapping/

### What is the issue?

The guidance includes an example:
```
if (PublicKeyCredential.isConditionalMediationSupported()) {
  navigator.credentials.get({
    mediation: "conditional",  
    publicKey: {
      challenge: ..., // server generated challenge value
      rpId: ..., // RP's domain name
      userVerification: "required", 
    }
  });
}
```

I believe the `isConditionalMediationSupported` API is now promise-based.
.
### Proposed changes

Perhaps change to something like...
```
if (typeof PublicKeyCredential != undefined && typeof PublicKeyCredential.isConditionalMediationAvailable != undefined) {
        PublicKeyCredential.isConditionalMediationAvailable()
        .then((result) => {
            if (result) {
                navigator.credentials.get({
                    mediation: "conditional",  
                    publicKey: {
                      challenge: ..., // server generated challenge value
                      rpId: ..., // RP's domain name
                      userVerification: "required", 
                    }
                  });            
            }
        });
}
```

### Any other notes

Even the example I've provided won't work in all browsers as this API is a bit of a moving target, so something different again is probably needed in the short term. Either way, what is provided on passkeys.dev today is no longer the strategic direction.

**Comment by MasterKale** [comment]
@sbweeden Thanks for reporting this, good catch. I've got #99 out to improve this part of the bootstrapping docs, can you give it a look and let me know if it's too much?

**Comment by timcappalli** [comment]
Thanks @sbweeden!

**Comment by sbweeden** [comment]
> @sbweeden Thanks for reporting this, good catch. I've got #99 out to improve this part of the bootstrapping docs, can you give it a look and let me know if it's too much?

I think it's fine. Personally I like the .then() form of handling a promise chain rather than async/await, but so long as you're consistent in the various code samples, no problem.
